import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const tanhaSans = localFont({
  src: "./fonts/Tanha.woff",
  variable: "--font-tanha-sans",
  weight: "100 900",
});
const tanhaMono = localFont({
  src: "./fonts/Tanha.woff2",
  variable: "--font-tanha-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tanhaSans.variable} ${tanhaMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
